### ISSUE TITLE
vim hangs on write with [Pymode] Regenerate autoimport cache when I edit .py files in ~

### ISSUE THREAD

**Issue by dwf** [klen/python-mode#525] opened 2015-01-19 15:26 UTC
So, I have a lot of stuff in my home directory (as I think many do) but I also occasionally write small Python scripts in ~ (as many, I think, do).

Is there any way to stop rope from regenerating the autoimport cache for a specific target directory?

**Comment by jonblack** [comment] 2015-01-20 07:51
I think this is a regression. Last week I didn't have this problem, and since then I've updated both vim and python-mode.

My `.vimrc` already had `let g:pymode_rope_lookup_project = 0`. By adding `let g:pymode_rope = 0`, rope is turned off so the problem can at least be avoided for the time being.

**Comment by vdrandom** [comment] 2015-02-06 22:14
I've been trying to get into using this amazing plugin, but ended up with the same problem. Thank gods it's only related to running vim from $HOME, but it's still a serious bug. =/

**Comment by fwang2** [comment] 2015-02-08 17:48
I am experience the same hang and downright sluggishness with rope turned on. I only experienced this with a recent update ... looks like a regression.

**Comment by ixtli** [comment] 2015-02-10 17:22
I am also experiencing this :/ I thought it had to do with using os.walk, but it appears to happen whenever I write a new .py file.

**Comment by mkzero** [comment] 2015-02-14 23:26
I'm having the same problem. I just had this problem in one of my dev directories with a virtualenv set up and it hangs and vim get's unuseable... The directory has ~3000 files in it; mostly files from the virtual env.

**Comment by Stolas** [comment] 2015-02-15 13:42
Same here.

**Comment by shahsaifi** [comment] 2015-02-18 17:42
i'm also experiencing same issue. Any luck?

**Comment by frimik** [comment] 2015-02-21 21:21
similar issue? 

seeing another OOM issue: upon opening a new file, starting to type (I got to the first dot after a class object), Pymode enters state: `[Pymode] Regenerate autoimport cache.`, vim is unresponsive and consumes all CPU and eventually all RAM:

` 3477 vagrant   20   0 2506m 2.2g 5112 R 98.1 60.0   5:20.49 vim`

This can happen at random it seems. Been working in this particular project directory for a while, even worked on this particular file in a previous buffer a few times...

**Comment by exhuma** [comment] 2015-02-23 10:46
I see the same issue. It seems to happen if I have not worked on a project for some time (a few hours). Even if I keep the vim window open.

**Comment by chipolux** [comment] 2015-02-23 21:42
Just chiming in, same issue here, for me it only happens when I'm in a directory with a large amount of files and sub-directories. It can chug away rebuilding the rope autoimport cache for a good minute or two in some of my larger projects.

**Comment by fabioedoardoluigialberto** [comment] 2015-02-24 16:19
Same here. Only affects home folder.

Deleting the `.ropeproject/` didn't work.

**Comment by jwhisnant** [comment] 2015-02-24 19:36
This config below seems to disable the behavior.  I confirmed with strace that vim is reading the many .py files in my home directory (and subdirectories) when it "hangs" on write.

" Complete keywords from not imported modules (could make completion slower)
" Enable autoimport used modules
call pymode#default('g:pymode_rope_autoimport', 0)

(referenced from http://faculty.cs.wwu.edu/~siemenr/public/configuration/vim/vim/bundle/python-mode/plugin/pymode.vim)

**Comment by wjstarrsiii** [comment] 2015-02-26 04:11
It is happening for me 3 folders deep in my homedir, with a virtualenv active.  I get the [Pymode] Regenerate autoimport cache everytime I type a ".", vim freezes, and when I continue typing the cursor inserts before the .  Very painful. Only 2 py files in this folder, but 503 total .py files in the venv subdirs.

**Comment by exhuma** [comment] 2015-03-06 10:12
I was just talking about it to my team-mates. Turns out, they were already all annoyed by this and completely disabled rope via `let g:pymode_rope = 0` in the `vimrc`

I have disabled it as well now. I barely ever use the rope features so it's not hurting, and may be a workaround for other people in here.

**Comment by exhuma** [comment] 2015-03-06 10:15
I just read through #537 and it seems the latest branch. I just tried to upgrade my python-mode (via Vundle), but it does not seem to be in `master` yet. I will wait until that happens to see if this fixes this issue.

**Comment by amghost** [comment] 2015-03-10 07:30
Same here

**Comment by ccope** [comment] 2015-03-12 19:44
+1. It seems that every time I trigger rope it regenerates my whole rope cache (which is for a large repo).

**Comment by AdrianRibao** [comment] 2015-03-18 15:35
+1. Same here

**Comment by sharkqwy** [comment] 2015-04-01 09:23
+1 really slow. Awful user experience.

**Comment by f0t0n** [comment] 2015-04-01 09:39
Seems I'm unlucky. Just starting moving to vim for Python development and got this issue. It would be nice to see it fixed.

**Comment by makiolo** [comment] 2015-04-01 09:49
work for me:
let g:pymode_rope_autoimport = 0

**Comment by ccope** [comment] 2015-04-01 22:30
#512 seems to fix this for me (ubuntu 14.04)

**Comment by AdrianRibao** [comment] 2015-04-21 23:39
This bug is making python-mode and vim unusable for me.

This is an extract of the most relevant profiling information after saving a file:

    FUNCTION  pymode#buffer_post_write()                                                                                                                                                                                                    
    Called 1 time                                                                                                                                                                                                                           
    Total time: 194.499101                                                                                                                                                                                                                  
     Self time:   0.001484 
    
    FUNCTION  pymode#rope#regenerate()                                                                                                                                                                                                      
    Called 1 time                                                                                                                                                                                                                           
    Total time: 193.062728                                                                                                                                                                                                                  
     Self time: 192.992593                                                                                                                                                                                                                  
                                                                                                                                                                                                                                            
    count  total (s)   self (s)                                                                                                                                                                                                             
        1   0.053510   0.000039     call pymode#wide_message('Regenerate Rope cache ... ')                                                                                                                                                  
        1 193.009202 192.992538     PymodePython rope.regenerate() 
    
    
    FUNCTIONS SORTED ON TOTAL TIME                                                                                                                                                                                                          
    count  total (s)   self (s)  function                                                                                                                                                                                                   
        1 194.499101   0.001484  pymode#buffer_post_write()                                                                                                                                                                                 
        1 193.062728 192.992593  pymode#rope#regenerate()

Let me know if I can help with anything else.

**Comment by wuranbo** [comment] 2015-05-08 03:17
I found a important reason.
** Because of virtualenv.  **
When I use virtualenv build the python env dir in my project path.
** The .ropeproject dir size become huge to 700k, everything become slow. **
But my own project with 2k python code only generate 100k  
** Solution is mv the env out of the project dir, and link it back as symbolic.

**Comment by squisher** [comment] 2015-05-08 21:44
I also have a virtualenv (and because of that about 2300 .py files in the subtree) and after updating from 0.8.1 the code checking became utterly slow. I bisected it to the following commit:

> commit 88dbf84c3e5f01dc9352240a75aa3c31438604cd
>Author: Brendan Maguire <maguire.brendan@gmail.com>
>Date:   Fri Oct 10 16:32:08 2014 +0100
>
>    Fixed some issues around the auto_import_cache
>    
>    * fixes #361
>    
>    * pymode_rope_autoimport_modules was never coming into effect during RopeContext __init__
>    * rope.regenerate now generates the cache for the entire project instead of just one file
>    * StringIO was been imported as a class, but been used as a module

**Comment by squisher** [comment] 2015-05-08 22:16
I tried the obvious fix by reverting the change on **pymode/rope.py:224**:
> - ctx.importer.generate_cache(resources=[ctx.resource])
> + ctx.importer.generate_cache()
but that caused some errors for me.

Setting
> let g:pymode_rope_autoimport = 0
did help somewhat (the startup time is still noticably slower than before)

**Comment by coolBean** [comment] 2015-05-11 17:04
At last, I use "brew uninstall vim" to solve it

**Comment by ntdef** [comment] 2015-05-12 14:14
+1. Rope is performing extremely sluggishly.

**Comment by miaoyin** [comment] 2015-05-25 04:08
thank you

**Comment by gg5673073** [comment] 2015-06-01 15:51
work :  let g:pymode_rope_autoimport = 0  append it in .vimrc

**Comment by FedericoCeratto** [comment] 2015-07-06 11:05
+1 It got to the point where I had to hard-reboot my workstation.

**Comment by balta2ar** [comment] 2015-07-14 17:13
Same here. Very slow, not cool!

**Comment by K-Guan** [comment] 2015-08-25 02:06
Same here, must I disable the rope? However I think that rope is a good feature.

**Comment by ccope** [comment] 2015-08-25 03:52
I recommend people who are still encountering this issue try patching #512 and report back whether or not that solves the problem (along with your OS version)

**Comment by K-Guan** [comment] 2015-08-25 04:20
ok, let me try it.

**Comment by frimik** [comment] 2015-08-25 08:38
So far, at least that patch didn't hurt!

`CentOS release 6.6 (Final)`

**Comment by K-Guan** [comment] 2015-08-25 11:46
@frimik well, I'm on Arch Linux and that patch didn't work.

**Comment by eyemyth** [comment] 2015-09-03 19:59
Working for me.

OS X 10.10.5
vim 7.4.712 via Homebrew

**Comment by dOpsCoder** [comment] 2015-09-08 08:32
No Joy. Still slow on save
RHEL 6.4
vim 7.4(compiled from source)

**Comment by klen** [comment] 2015-09-08 12:45
I have disabled 'autoimport' feature by default (looks like people dont use it anyway). Also I recommend check `.ropeproject/config` file and edit prefs.ignored_resources if pymode is running slow. Sorry guys for the inconveniences.

**Closed by klen** 2015-09-08 12:45 UTC

**Comment by nuklea** [comment] 2016-04-12 03:23
Have same issue. `:let g:pymode_rope = 0` helps.

**Comment by racekiller** [comment] 2016-04-30 16:44
Thanks that help disabling rope.
Now I want to have jedi to autocomplete but seems to be that works bad with pymode
any comment?

thanks

**Comment by hholst80** [comment] 2016-09-28 07:34
VIM 8 crashes for me on this. I will try the `let g:pymode_rope = 0` thing and see if that workaround works.
![image](https://cloud.githubusercontent.com/assets/6200749/18904536/bc682b3e-855e-11e6-9c8e-0beaccf14477.png)

**Comment by sanjay555** [comment] 2017-01-26 16:56
Work :+1:  let g:pymode_rope_autoimport = 0

**Comment by Xunius** [comment] 2017-02-09 02:42
`let g:pymode_rope_autoimport=0` doesn't work. On Manjaro with Vim 8.0.237.
Can't believe the dev just closed this unsolved issue, wtf?

**Comment by skamsie** [comment] 2017-02-22 20:45
```:let g:pymode_rope = 0``` disables rope completely which means no go-to-definition for external packages, no autocomplete for external packages, etc... Simply adding
```let g:pymode_rope_regenerate_on_write = 0``` to .vimrc makes this bug not reproduce (check title).

Since a lot of people get into this issue and it can be a very disappointing first experience I would suggest the maintainers to start with it disabled by default... I am not ever sure what exactly does in the first place. Other than that very good plugin!

**Comment by codeMagnet78** [comment] 2017-02-25 11:26
let g:pymode_rope = 0 
let g:pymode_rope_lookup_project = 0 
let g:pymode_rope_complete_on_dot = 0
let g:pymode_rope_autoimport = 0

This resolved the issue in my case.

**Comment by h3** [comment] 2017-03-20 17:08
@codeMagnet78 That worked for me too, thanks.

**Comment by Benhgift** [comment] 2017-05-31 11:02
@codeMagnet78  but that disables rope. Rope is the best part of this plugin. I only installed this for goto_definition(). 

Is there a way to keep rope from activating if it's not in a git controlled directory? Or at least from recursively searching?

**Comment by Benhgift** [comment] 2017-05-31 19:22
@klen any chance of letting me add an option to py-mode for this? Something like `g:pymode_rope_activate_if_git_repo` maybe?

**Comment by wandersoncferreira** [comment] 2017-07-08 14:49
@Benhgift It worked just fine for me! thanks!

However, I had to install `pip install GitPython` in order this to work out!

**Comment by shaypal5** [comment] 2017-10-23 13:55
@Benhgift 

Hey man, thanks so much! It worked great!

**Comment by praveenkumark1508** [comment] 2018-02-20 20:55
Is it possible to make rope to regenerate cache asynchronously in vim80?

**Comment by alphaCTzo7G** [comment] 2018-04-01 00:51
@praveenkumark1508 , I was thinking the same. I know for `gutentags`, the tag generation happens continuously and doesnt block vim. Perhaps something like that can be implemented.

**Comment by alphaCTzo7G** [comment] 2018-04-02 15:39
I didnt want to disable rope, but I notice the slowness happens only when rope tries to redo the cache. 

By default, rope regenerates the cache on write, because of the setting

    let g:pymode_rope_regenerate_on_write = 1

is set when `pymode` is imported.

After I disabled it, the slowness went away.

Now, when I want to generate the cache, I just use

:PymodeRopeRegenerate

Also I noticed that the rope-vim project has alot more options than this repo:

https://github.com/python-rope/ropevim

Perhaps the rope in this project is too old.

**Comment by diraol** [comment] 2018-04-02 17:54
Hi friends!
@fmv1992 worked a lot to remove the copied code from our dependencies and did a great job on that for many dependencies (specially linters). But some of them are still code-copied under our repo [https://github.com/python-mode/python-mode/tree/develop/pymode/libs].

It would be wonderfull if you can contribute with us by removing this dependency as they are and add them as submodules [https://github.com/python-mode/python-mode/tree/develop/submodules], so we can keep these dependencies more updated.

Also, about the async stuff, sure it may be possible, but I have no idea how to do it. =/

Btw. Let's open another issue for this rope "migration" (from copied code to submodule) and discuss over there?

**Comment by ViktorBarzin** [comment] 2018-04-12 12:51
Hi all,

I am experiencing the same issue for a while and it occurs only when the folder contains many files (for example $HOME).

I'm not sure how the plugin works but why not add the option to ignore lookup directories so you can explicitly ignore some directories to lookup?

**Comment by Benhgift** [comment] 2018-04-12 17:10
@vikt0rs I you use the fix I posted then it'll only kick in for git repos. You could tweak that to omit directories instead

**Comment by alphaCTzo7G** [comment] 2018-06-02 17:29
@diraol , you guys should consider writing new functionalities in `python` instead of `viml`. IMO, very few people would want to learn `viml` as such will have few contributors. From what I understand `neovim` has a pretty good `python client`: https://github.com/neovim/python-client

**Comment by diraol** [comment] 2018-06-02 18:07
@alphaCTzo7G I think your suggestion makes a lot of sense, especially because I personally don't know `viml`.

But I still need to better understand how to (re)write vim plugins, even using python.

Unfortunately, I am facing a lack of free time to dedicate myself to python-mode despite some minor fast fixes and trying to answer some questions on our issues =/

**Comment by alphaCTzo7G** [comment] 2018-08-01 18:15
@diraol .. its relatively simple.. take a look at this plugin which I am looking into a bit: https://github.com/FelikZ/ctrlp-py-matcher/blob/master/autoload/pymatcher.py

The `python` interface is well documented here: http://vimhelp.appspot.com/if_pyth.txt.html#python-vim

A lot of the interface is already available directly. If it is not available.. the general idea is to use something like `vim.eval` or `vim.command` to evaluate a `viml` command and pass the output to the python namespace. Then do the heavy computation in `python` and pass it back to `vim`.

`ctrlp-py-matcher` just does that.. and it gets massive improvement in speed. I can basically search through a 500Mb linux kernel tag file in a few secs using `CtrlPTag`, while if I just used `CtrlP` and the `vimL` engine.. I tried waiting for 15mins.. and it never gave me any results..

**Comment by alphaCTzo7G** [comment] 2018-08-01 18:17
Also thought I would mention that @Benhgift 's solution works great.. and I have been using it. However, if you are working in a virtualenv, where the `git` library is not included, the following command

```
python3 << EOF
import vim
import git
def is_git_repo():
    try:
        _ = git.Repo('.', search_parent_directories=True).git_dir
        return "1"
    except:
        return "0"
vim.command("let g:pymode_rope = " + is_git_repo())
EOF
```

will break. Perhaps the `git` module can be packaged with `python-mode` or the code above should be modified to always use the `system` python installation

**Comment by bhattbhuwan** [comment] 2021-06-21 08:15
> `:let g:pymode_rope = 0` disables rope completely which means no go-to-definition for external packages, no autocomplete for external packages, no refactoring, etc... Simply adding
> `let g:pymode_rope_regenerate_on_write = 0` to .vimrc makes this bug not reproduce (check title).
> 
> Since a lot of people get into this issue and it can be a very disappointing first experience I would suggest the maintainers to start with it disabled by default... I am not even sure what exactly does in the first place. Other than that very good plugin!

This solution worked for me
